### PR TITLE
Fix cross compiling bug in AC_CONFIG_SUBDIRS in configure.ac

### PR DESCRIPTION
**Pull request by evrim**
Fix cross compiling bug in AC_CONFIG_SUBDIRS in configure.ac
while recursively configure yasm package.

### CODE REVIEW

**Comment by evrim** [comment]
Please see configure.ac and the following link:
http://lists.gnu.org/archive/html/autoconf/2015-02/msg00015.html

**Comment by wbhart** [comment]
Thanks. We'll take a look at this and try to merge it.

**Comment by jpflori** [comment]
I'd be in favour of getting rid of the included yasm directory and let the user build it himself (or use a system-wide).
Hacking autoconf to configure and build yasm is painful.

**Comment by evrim** [comment]
Interesting. What you say is a problem in most projects. I'm trying to find
a way using git submodules. Let me know if there is a way.

The fix is no hack. Just removal of a customization.

Maybe changing configure.gnu contents to configure $@ would be a cleaner
fix. It doesn't pass the params correctly now.

Best,
evrim.

**Comment by jpflori** [comment]
The real problem with including the yasm subdir is that:
* yasm files are tracked but we don't really care,
* there is no easy way to pass options to yasm through configure,
* we have to patch the yasm Makefile to modify some targets, e.g. install which would fail as yasm does not get the configure prefix value,
* some make targets are still half broken IIRC...

**Comment by evrim** [comment]
On Feb 25, 2015 8:12 PM, "Jean-Pierre Flori" <notifications@github.com>
wrote:
>
> The real problem with including the yasm subdir is that:
>
> yasm files are tracked but we don't really care,

Absolutely true, the catch here is I guess to guarantee a working version
because yasm ppl can break randomly.
So if it is possible to include it as a git submodule and fix it to a tag
or branch it might be able to avoid the tracking using git submodule update
.

> there is no easy way to pass options to yasm through configure,

Agreed! I've been looking for a way to pass custom params to
AC_CONFIG_SUBDIR yet no luck.
Any ideas?

> we have to patch the yasm Makefile to modify some targets, e.g. install
which would fail as yasm does not get the configure prefix value,

Everybody has the same problem, there is a hack in autotools that
particularly targets prefix problem. Gee..

> some make targets are still half broken IIRC...
>
> —

Best,
Evrim.

**Comment by wbhart** [comment]
Unfortunately I can't merge this patch because I can't tell what is part of the patch and what is part of autoreconf whalloping our build system.

For example, config.guess and friends have been overwritten. We need special versions of these in MPIR.

There's also a bunch of new files I don't recognise.

Was the change to configure.ac the only change actually needed?

**Comment by jpflori** [comment]
I guess this pull request is obsolete now mpir does not ship yasm anymore.

**Pull request closed without merging**
