### PR TITLE
Autotools

### PR DESCRIPTION
**Pull request by jpflori**
Stop tracking autogenerated files and a script to autogenerate them.

### CODE REVIEW

**Comment by wbhart** [comment]
Oops, I think I might have just broken this. :-(

**Comment by jpflori** [comment]
I've hopefully force pushed a mergeable branch.

**Comment by wbhart** [comment]
Thanks.

**Comment by isuruf** [comment]
@jpflori, you need to run the new script [here](https://github.com/wbhart/mpir/blob/7819de462062d46bcd2d3b73b3a496bd76033e43/.appveyor_msys_build.sh#L3) as well.

**Comment by wbhart** [comment]
@isuruf Note that --with-system-yasm is no longer needed (or accepted). It is the default.

**Comment by wbhart** [comment]
Sorry, I think I just unintentionally broke it again.

**Pull request merged**
