### PR TITLE
MPIR.Net solutions added for Visual Studio 2012, 2013, and 2015.

### PR DESCRIPTION
**Pull request by adyache**

### CODE REVIEW

**Comment by wbhart** [comment]
My first impression is that this is a high quality contribution. The code looks neat and comprehensible and the design is technically sophisticated. I will need to take a closer look, and we will want to include documentation in the manual. But at this stage I can definitely see us including this.

**Comment by wbhart** [comment]
Thanks for your patience with this. Sorry for the long delay. For some reason I didn't get any notification that the directory move to mpir.net had occurred. So I thought I was still waiting for this.

The code looks good, with a few comments:

* Could you add some comments to the changes made to gmp-h.in to explain that these changes were added to support the mpir.net project, just so people won't get confused, or remove the lines you've added.

* Could you explain briefly the changes made to the IO functions, why they were necessary, and also assure us that they do not change the contract of these functions, i.e. the format of what they input or output. It's scary to change functions so fundamental as these. Many users could be affected if we get it wrong. If those changes are only necessary for the mpir.net project, I wonder if it makes sense to add a configure flag to build for mpir,net. What do you think? Alternatively, a few more code comments to note exactly which changes are purely for .net would be helpful.

I am personally quite happy to merge this once we've signed off on these two things.

**Comment by adyache** [comment]
I have moved all the gmp-h.in changes to gmp-impl.h instead.  gmp-h.in now stands unchanged, and I have added comments to the additions in gmp-impl.h, as well as in the out_raw.c and inp_raw.c sources to explain what was changed and why.  Sorry, with the size of the pull request the diffs in these last two are not shown on github.

**Comment by wbhart** [comment]
Sorry for the delay on this. According to Travis, the build currently fails due to issues in mpir.texi, which is presumably due to the documentation changes you pushed. Perhaps you could take a look at the build logs on travis [1] and see if you can fix these. Otherwise I am happy to merge this.

[1] https://travis-ci.org/wbhart/mpir/builds/138165621

**Comment by adyache** [comment]
I have fixed the build.  No problem on the delay, it’s all good!

 

Thanks,

Alex

**Pull request merged**
