### PR TITLE
Remove old deleted folder.

### PR DESCRIPTION
**Pull request by jpflori**

### CODE REVIEW

**Comment by wbhart** [comment]
@isuruf It looks like appveyor is failing due to yasm being too old to compile for the machine appveyor is using.

**Comment by isuruf** [comment]
@wbhart, it's using 1.3.0 which I believe is the latest version.

**Comment by wbhart** [comment]
Oh that's interesting. It doesn't recognize XMM registers. I'll try rerunning the build.

**Comment by wbhart** [comment]
@isuruf Nope, it still fails. It's odd because yasm-1.3.0 assembles the haswell assembly code fine on my machine. Perhaps the problem is in a Windows only section of the code. I'll check that.

**Comment by isuruf** [comment]
Looking at the appveyor logs, it was introduced in this merge commit, https://github.com/wbhart/mpir/commit/adec7e7871664ba4ba9e500f1739fbd0c6c35540

**Comment by wbhart** [comment]
@isuruf Hmm, that change was made to support the latest version of sed. But why is that even a problem. It shouldn't affect the yasm macro in question, which is indeed only in the Windows only part of the code.

**Comment by wbhart** [comment]
@isuruf I suppose we could try reverting that change and seeing if it fixes the issue. If so, we can figure out why, and how to fix it. I'll try it now.

**Comment by isuruf** [comment]
@wbhart, that's a merge commit, it's the other parent that is problematic. Specifically @akruppa's changes.

**Comment by wbhart** [comment]
@isuruf Well the good news is that patch had nothing to do with the problem. I tried reversing it on a branch, but the same thing happens.

**Comment by jpflori** [comment]
Can we still this branch?
It just removes a non-existent folder from Makefile.am.
Without this commit, make dist fails.

**Comment by wbhart** [comment]
@isuruf You mean this one https://github.com/wbhart/mpir/commit/160fd98d1acaa038286b393fe0baa0406b233546

There's nothing in there that should affect the assembly language.

**Comment by isuruf** [comment]
@wbhart https://github.com/wbhart/mpir/commit/12ffe87475a3a04b682ee7a63949cc60e5416ad0 and all the previous ones.

**Comment by wbhart** [comment]
@isuruf Ah, yeah those commits include the ones where the assembly files in question were added. So for some reason yasm just isn't handling the Windows only parts of those files. I'll chat to @BrianGladman about this, since he is using yasm to compile these under MSVC.

**Pull request merged**
