### PR TITLE
System yasm

### LINKED ISSUE #188: Use system yasm instead of bundled yasm
We should remove the bundled yasm and depend on a system one. This will make packagers happy.

### PR DESCRIPTION
**Pull request by jpflori**
Closes #188.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks. I will hold off merging this until people have had a chance to get tuning values, as making people install yasm first will probably put people off doing this otherwise.

**Comment by wbhart** [comment]
As this changes 1326 files, I can't easily review this patch.

Does it:

* allow someone to specify where to find yasm (in case they don't have root access to install it system wide)?

* make changes to the documentation to document how MPIR should now be built?

* make all the necessary changes to configure.ac to build yasm files using yasm instead of ../yasm/yasm?

**Comment by jpflori** [comment]
Note that among the 1326 modified files, 1324 belong to the yasm folder.
The only relevant changes are to configure.ac and Makefile.am at the top level.

I did not add doc yet.
Right now, you can either pass no option to configure and it will try `which yasm`, or pass "--with-yasm=<path to yasm>".
In both cases it will make a minimal check as used to be done: the file exists and is executable.

**Comment by wbhart** [comment]
Did you remove the --with-system-yasm option?

Do you think you will have time to update the docs?

I think we might end up with a lot of users reporting bugs if we don't test
for a specific version of yasm. But we can try it and see how we go I guess.

**Comment by jpflori** [comment]
Yes I only kept the --with-yasm=... one.
The default behavior (i.e. without passing --with-yasm=...) is the same as the previous --with-system-yasm, i.e. try to locate yasm with `which yasm`.

I'll add some doc later today or tomorrow hopefully.

**Comment by wbhart** [comment]
Thanks. It's much appreciated!

**Comment by jpflori** [comment]
Added some doc at the top of the installing MPIR section, and modified the doc for the --with-yasm option.

**Comment by wbhart** [comment]
Thanks. There's two other things that needs fixing now:

* travis-CI to build yasm
* appveyor to build yasm

**Comment by wbhart** [comment]
Although perhaps @isuruf may be able to fix CI for yasm?

**Comment by jpflori** [comment]
I guess I can make the needed modifications to .travis.yml and make travis install yasm.

**Comment by jpflori** [comment]
It seems appveyor is only used for msvc and mingw and already installs yasm.

**Comment by wbhart** [comment]
That's true. Thanks.

**Comment by wbhart** [comment]
It doesn't look like it found yasm.

**Comment by jpflori** [comment]
I wrongly assumed from https://github.com/travis-ci/travis-ci/issues/4495 it was available...

**Comment by isuruf** [comment]
It is getting installed. https://travis-ci.org/wbhart/mpir/jobs/201505183#L163
Why is the configure script creating a yasm folder here, https://travis-ci.org/wbhart/mpir/jobs/201505183#L436-438 ?

**Comment by jpflori** [comment]
Oh, it correctly installed yasm actually.
The issue is that I did not run autoreconf...

IMHO we should not include all the autotools generated stuff in the git repo.
It produces huge diff when updated and must be updated quite frequently.

**Comment by wbhart** [comment]
You are probably right, but it makes it impossible to do a source build from Julia unless the user has autotools installed on their machine, which is unlikely.

**Comment by jpflori** [comment]
Note that it should still be shipped with releases.
Does julia build mpir from the git version?

**Comment by wbhart** [comment]
Actually, no. Julia builds from a tarball. The problem is, make dist can't create a tarball unless the files are under source control. There's probably a way around this, but I don't know what it is.

**Comment by wbhart** [comment]
Also autoreconf -fiv throttles config.sub, config.guess and ltmain.sh, which we have to supply hacked versions of. So it really wouldn't be practical to not include everything in git.

**Comment by jpflori** [comment]
We should look at what option GMP pass to autoreconf, I think -fiv is a little too violent.
We surely have to drop -f.
They use -is.
See https://gmplib.org/repo/gmp/file/tip/.bootstrap.

**Comment by jpflori** [comment]
We can also add an autogen.sh script (or .bootstrap to mimick GMP rather than the rest of the world) to update the config.* script correctly.

**Comment by jpflori** [comment]
I can also take care of the make dist hook if you want.

**Comment by wbhart** [comment]
If you are able to make it all work, go right ahead. But I'm sceptical that it won't break something. We also hack configfsf.guess etc. I think, because a bunch of things are missing from the standard config.guess (which this is supposed to be).

**Comment by wbhart** [comment]
The other annoyance is every system has a different version of autotools and every single one breaks something in our configure, except the one we use (which is actually specially hacked for Windows). In short, I am almost certain lots of things will break if you go down that track.

**Comment by jpflori** [comment]
That may be an issue, but note that with released tarballs the user won't have to run autotools, mitigating most of the issues.
Playing with the git version shouldn't be attempted by the mondane user.

**Comment by wbhart** [comment]
Yes, I guess so. But it'll be a burden for developers, in my opinion.

**Comment by wbhart** [comment]
By the way, I think I've essentially run out of other things to do now. Unless someone supplies Broadwell support or something like that, I'm basically ready to cut an alpha once this ticket is resolved.

**Comment by jpflori** [comment]
On my side it's a pain to deal with the diff's of autoreconf and make sure I don't "update" to old versions depending on the sytem I'm on when developping :)

**Comment by wbhart** [comment]
Sure. I simply suspect you may be underestimating the profundity of the issues with autotools wrt MPIR. If you think you can sort it out, go right ahead. But I need to issue an alpha today or tomorrow at the latest if I can. (I won't be able to work on MPIR after 28 Feb, and so the entire release process needs to be done by then, including alphas and release candidates).

**Comment by jpflori** [comment]
I now have something working.
Note that make dist is smart enough to ship the generated Makefile.in, configure and other scripts generated by libtool.
Do you want me to push it on another branch or here?

**Comment by wbhart** [comment]
I think I'd prefer it in a separate branch. This branch is so close to being ready to merge, I'm just worried we'll lose it if we don't commit it now.

Looks like I have another ticket to fix anyway (probably will be tomorrow morning now), as fat binaries are broken.

**Comment by wbhart** [comment]
I'd like to see Travis pass on this PR before merging of course.

**Comment by jpflori** [comment]
I can only achieve this by running autoreconf...

**Comment by wbhart** [comment]
Yes, that's what I was hoping you would be able to do. Alternatively I can run it and push the changes for you to merge into this branch. The procedure is:

autoreconf -fiv --no-recursive
git checkout config.guess
git checkout config.sub
git checkout ltmain.sh

You might not need the --no-recursive now, of course, since yasm is gone.

**Comment by jpflori** [comment]
I'd prefer you to do it. The version of autotools I have access to right now is different and will produce unnecessary changes.

**Comment by wbhart** [comment]
Sure, no problem. I'll do it right now.

**Comment by wbhart** [comment]
Ok, you should see my system_yasm branch now.

**Comment by jpflori** [comment]
Yup, just merged your branch and pushed mine back.

**Comment by wbhart** [comment]
As soon as it passes, I'll merge this PR and close those two tickets. Do you want me to create a ticket for removing Makefiles and configure from version control?

**Comment by jpflori** [comment]
Sure go ahead.
As you must have noticed, I made a PR for it already!

**Comment by wbhart** [comment]
Ok, it's #205

**Comment by wbhart** [comment]
Looks like it's failing to find yasm on OSX.

**Comment by isuruf** [comment]
See https://github.com/jpflori/mpir/pull/1

**Comment by wbhart** [comment]
Thanks Isuru. I'll wait for JP to merge this, and then we should be ok, I
think.

**Pull request merged**
