### PR TITLE
Comparison between mpq and mpz

### PR DESCRIPTION
**Pull request by videlec**
Add a function mpq_cmp_mpz that compares mpq with mpz. That mostly avoids one allocation/deallocation when we want to compare a rational with an integer.

### CODE REVIEW

**Comment by videlec** [comment]
Why isn't this merged anywhere!?

**Comment by wbhart** [comment]
Very good question! It looks like I accidentally closed the PR instead of merging it.

I'll check and see if that's what happened.

**Comment by wbhart** [comment]
Yep, it's definitely not in there. We have to do a new minor release anyway, due to the fact that some assembly files seem to be broken on Windows. So I hope it won't be too long before we fix this. I've reopened the PR. Sorry about that!

**Comment by videlec** [comment]
No problem you had a lot to deal with... I need to fix the merge issues right?

**Comment by videlec** [comment]
I was wrong, you can close the issue. The function implemented is mpq_cmp_z (available from 8862bcda) and not mpq_cmp_mpz (what this PR is about)... sorry for the noise.

**Pull request closed without merging**
