### PR TITLE
Import the implementation of mpq_cmp_z from gmp

### PR DESCRIPTION
**Pull request by videlec**

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks Vincent, this is great.

Is there documentation for doc/mpir.texi?

**Comment by videlec** [comment]
I copied the one line of documentation from gmp.

**Comment by wbhart** [comment]
I also just noticed you haven't added your name to AUTHORS!

**Comment by videlec** [comment]
Actually, I am a translator. I should really give credit to the one who really did the job in gmp: Marco Bodrato, Marc Glisse, Torbjörn Granlund, Niels Möller...

**Comment by wbhart** [comment]
Thanks Vincent. This looks to pass all tests and the code looks ok to me. We'll merge this as soon as we finally get time to get back to MPIR-2.7.1.

I could merge it right now, but I think it best to keep changes to the interface together in 2.8.0 which will effectively bring us up to date with GMP-6.0.0.

**Comment by wbhart** [comment]
I've now merged this into master. Thanks to all the authors!

**Pull request merged**
