### PR TITLE
fix issue 230

### PR DESCRIPTION
**Pull request by dimpase**
fixes https://github.com/wbhart/mpir/issues/230

### CODE REVIEW

**Comment by dimpase** [comment]
It's a OSX homebrew thing with installing gcc4.8 that should be fixed. @isuruf - do you know how?

**Comment by isuruf** [comment]
Ref: https://github.com/travis-ci/travis-ci/issues/8826

**Comment by dimpase** [comment]
the commit https://github.com/wbhart/mpir/pull/238/commits/a72fd9fdbee20111f4e13696dab0287b3017fa0b I just added here appears to work - as a workaround.

**Comment by wbhart** [comment]
Thanks Dima.

**Pull request merged**
