### PR TITLE
asm syntax fixes for allow for different JMPENT, and ignore more stuff in .gitignore

### PR DESCRIPTION
**Pull request by dimpase**
addresses https://github.com/wbhart/mpir/issues/233

### CODE REVIEW

**Comment by dimpase** [comment]
no wonder it fails on Travis' OSX - as there is no patch for JMPENT included in the pull request. However, it does not complain about `addmul_1.o`, but about some other file.

**Comment by dimpase** [comment]
travis-ci is too nosy sometimes. I didn't mean to update the pull request as yet...

**Comment by wbhart** [comment]
Ok, just let me know when you are ready. If you push to that branch it will
update the PR. It's not a problem.

**Comment by dimpase** [comment]
https://travis-ci.org/dimpase/mpir/jobs/305917760 shows that at least we now have conditional on OSX version of JMPENT in the right place, autoconf/m4-wise. 

By the same `t-fat` and `t-sizeinbase` tests fail on the clang build. We'll see if it's the same on the `gcc` build soon.

**Comment by wbhart** [comment]
The t-divrem_1 failure is a bit hard to understand. The mpn_divrem_1 function is pretty simple, calling only mpn_divrem_euclidean_qr_1 which is implemented in this case in mpn/x86_64/divrem_euclidean_qr_1.as.

There's nothing dodgy looking in there. Also, it doesn't fail on other systems.

We might have to put some printf's in there to see what is going wrong and where. The other failure probably occurs for the same reason, but would be harder to debug, so let's work on the divrem_1 failure first.

**Comment by dimpase** [comment]
it's actually `t-sizeinbase`, not `t-divrem_1` (with the dynamic build).

**Comment by wbhart** [comment]
sizeinbase should be an even simpler function. It's hard to imagine it being buggy.

**Comment by wbhart** [comment]
Yeah I don't believe t-sizeinbase is faulty. There must be something else
underlying these failures.

**Comment by wbhart** [comment]
But yes, I misread the failure. It's not t-divrem_1, but t-fat and t-sizeinbase that fail. But I don't know how t-fat could fail. We're not building a fat binary. I'm sure what wouldn't work on a Mac anyway.

**Comment by dimpase** [comment]
t-sizeinbase dies before `mpn_sizeinbase` is called, somewhere in the assembler code of `sqr_basecase` called from mpn_pow_1 (line 81 of t-sizeinbase.c) via mul_n.c:351
(mpn_sqr_basecase (p, a, n);)

```
    frame #0: 0x00000001000866eb t-sizeinbase`__gmpn_sqr(p=0x0000000101000a10, a=0x00007fff5fbff978, n=1) at mul_n.c:351
   348 	    }
   349 	  else if (BELOW_THRESHOLD (n, SQR_KARATSUBA_THRESHOLD))
   350 	    {
-> 351 	      mpn_sqr_basecase (p, a, n);
   352 	    }
   353 	  else if (BELOW_THRESHOLD (n, SQR_TOOM3_THRESHOLD))
   354 	    {
```

 the library (dynamic or static) knows that it's built from `tmp-sqr_basecase.s`, which isn't preserved in the building process. Is there a way to keep it?

Then one would at least know more exactly where it dies; at the moment I only see
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xfffff7defffff793)
    frame #0: 0xfffff7defffff793
error: memory read failed for 0xfffff7defffff600
```

**Comment by wbhart** [comment]
I'm not aware of any way to make it keep the .s file. You can regenerate it
yourself by applying m4 to it. That's how I normally see what's in it.

Anyway, this now makes more sense. I guess there's a bug in
mpn/x86_64/sqr_basecase.asm. This file at least has JMPENT in it, so
there's a good chance this is to do with the changes we've made.

It might be worth comparing the file with the one in GMP to see if
something has been corrupted along the way. I don't see anything other than
the JMPENT's that could be problematic, short of corruption. It's very
surprising that there are no problems on other systems though, which makes
me suspect the JMPENT's as the source of the issue.

**Comment by wbhart** [comment]
I guess on OSX PIC should be false. You could check that this is the case
somehow. That could also be a potential issue.

**Comment by dimpase** [comment]
By the way, `t-fat` also dies at this function `mpn_sqr_basecase`
(more specifically, at the 1st run of this loop):
```
    frame #0: 0x0000000100001646 t-fat`check_functions at t-fat.c:292
   289 	  for (i = 0; i < 2; i++)
   290 	    {
   291 	      xp[0] = 5;
-> 292 	      mpn_sqr_basecase (wp, xp, (mp_size_t) 1);
   293 	      ASSERT_ALWAYS (wp[0] == 25);
   294 	      ASSERT_ALWAYS (wp[1] == 0);
   295 	    }
Target 0: (t-fat) stopped.
(lldb) thread step-over
Process 83880 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x10022db5f)
    frame #0: 0x000000010022db5f libmpir.23.dylib
->  0x10022db5f: addb   %al, (%rax)
    0x10022db61: addb   %al, (%rax)
    0x10022db63: addb   %al, (%rax)
    0x10022db65: addb   %al, (%rax)
```

**Comment by dimpase** [comment]
on OSX PIC must be on for shared libraries, for sure. That's in fact the whole point of this `darwin.m4` hack done originally by GMP people.

**Comment by wbhart** [comment]
Probably you are right. The documentation I thought was saying it should be off for OSX was actually talking about something else. I can't find any relevant Mac documentation on this. I guess it is only really ancient Macs that needed nopic.

**Comment by wbhart** [comment]
At least everything is passing on Travis now. But it's still failing on your machine?

**Comment by dimpase** [comment]
yes, I think that my machine is not good enough for this stuff - Apple does not test their new toolchains on "late 2010" hardware, and it obviously has some very unique bugs. Need outside tests for anything definite.

**Comment by wbhart** [comment]
That latest change seems to have brought back failures.

**Comment by wbhart** [comment]
It's possible Travis has multiple different OSX machines with different arches, some of which fail.

**Comment by wbhart** [comment]
Yeah that latest failure was for Nehalem. We will need to apply the same L() fix for all x86_64 arches.

**Comment by dimpase** [comment]
see https://github.com/wbhart/mpir/commit/4fe8708be99bce47e9766f2ec11519b319590c72#commitcomment-25809275 - that was a static build. Now back to dynamic, and failing. I have asked for a test on a "proper" skylake, we'll see if it works.

**Comment by wbhart** [comment]
Yeah, see my last comment for the reason why.

**Comment by dimpase** [comment]
What exactly is that `L()` doing? Do *.as files need this as well as *.asm files?

**Comment by wbhart** [comment]
No, the *.as files are not M4 processed, so don't need the L(). I think it is just a macro to autogenerate labels with some flexibility (for hacks for old assemblers, or something).

**Comment by dimpase** [comment]
I think I have added all the L()'s to the asm files used on skylake, but to no avail, testers report here a lot of test errors. So this probably means that skylake code with Xcode 9 needs
real work https://trac.sagemath.org/ticket/24085#comment:38

**Comment by wbhart** [comment]
Thanks for trying. My guess is there is a stupid bug somewhere in one of the assembly functions in the ifdef PIC part, which would explain why we get this with shared libraries. Why on earth it affects only OSX I have no idea. Perhaps the fix the GMP guys have for the JMPENT's is invalid, or we aren't applying it correctly.

Please leave this PR open, as this is all work that needed to be done anyway.

The only way to proceed from here is to run "try" on all the assembly functions, on an actual OSX machine where failures are occurring. This would narrow down the one that is broken (though I am betting it is sqr_basecase.asm).

**Comment by wbhart** [comment]
Actually, you could try removing sqr_basecase.asm and see if that causes the tests to pass. You may have to replace it with an earlier version without the jump table. Of course, if sqr_basecase.asm is available in any of the directories it searches for skylake, it will use it. So you have to remove it in lots of places.

**Comment by dimpase** [comment]
given that errors on my old core2 box match ones on Travis (nehalem), I guess my box can be used to get to the root of it. Perhaps it's some alignment corner case...

**Comment by dimpase** [comment]
a silly question - what is the purpose of the jump table? It seems that all it does is that it keeps relative addresses, and this perhaps saves space? I dunno...

**Comment by wbhart** [comment]
The answer to that is beyond the scope of a comment on GitHub. It's to do with rip relative addressing and is roughly the equivalent of a switch statement in C, I believe.

It's really curious that it works on Linux and not OSX. I think either PIC is not turned on on a Mac, or the GMP fix is not correct.

**Comment by wbhart** [comment]
If you want to help track down the issue, you could "make try" (can't recall which directory, maybe devel) and then try each of the mpn assembly functions in try (it gives instructions on how to use itself). Perhaps we can rule some things in or out with that approach. My guess is it is jumping off into the aether when it encounters one of those JMPENTs.

**Comment by dimpase** [comment]
PIC is really turned on on Darwin: namely, if I replace https://github.com/dimpase/mpir/blob/master/mpn/x86_64/darwin.m4#L10 with
the PIC case, i.e.
```
    `.set   $1_tmp, $1-$2
    .long   $1_tmp'
```
and build with `disable-shared` I get exactly the same errors as in the sharedlib (i.e. PIC) case (and these errors do not appear in the normal  `disable-shared` build).

**Comment by dimpase** [comment]
well, yes, I know computed GOTO in FORTRAN |V ;-)

The thing is that apparently OSX ld messes with the jumptables - do they provide external entry points? If not, getting rid of them should not be a problem...

**Comment by wbhart** [comment]
I don't know what external entry points are. You really can't get rid of the jump tables. The objective of assembly code is not to get something that works, but to get something optimal. Even a single change of a byte in the assembly code renders it effectively useless, since it is no longer optimised and needs to go through the entire optimisation process again.

Here is a description of what this code is supposed to do:

	lea	.Ltab(%rip), %rax  /* load the rip relative address of the table into rax */
ifdef(`PIC',
`	movslq	(%rax,%rcx,4), %r10  /* multiply rcx by 4 to give offset into table, and sign extend value in table at that offset, inserting it into r10 */
	add	%r10, %rax /* add the sign extended value from the table to rax *./
	jmp	*%rax /* jump to that address */
',`
	jmp	*(%rax,%rcx,8)
')
	JUMPTABSECT
	ALIGN(8)
.Ltab:	JMPENT(	.Ll4, .Ltab) /* compute the table relative address of l4, 32 bits only */
	JMPENT(	.Ll1, .Ltab)  /*  compute the table relative address of l1, 32 bits only */
	JMPENT(	.Ll2, .Ltab)
	JMPENT(	.Ll3, .Ltab)
	JMPENT(	.Ll0m4, .Ltab)
	JMPENT(	.Ll1m4, .Ltab)
	JMPENT(	.Ll2m4, .Ltab)
	JMPENT(	.Ll3m4, .Ltab)
	TEXT

.Ll1:	mov	(up), %rax /* first in a series of labels that can be jumped to */

**Comment by wbhart** [comment]
To answer  a previous question, L() is defined near the end of mpn/asm_defs.m4. All it does is add the local symbol prefix (probably .L), defined in config.m4, to the beginning of the symbol.

Technically we are supposed to be using LDEF() for the labels themselves, not L(), but this definitely isn't the issue here. All it prevents are trailing ...'s being interpreted as argument lists, otherwise it is identical to L().

**Comment by wbhart** [comment]
There's some information here [1] which I don't understand, but which we can try. In particular, we can try dropping the dot from the local symbol prefix, since OSX probably always uses the LLVM assembler. This would be fixed in config.h I think, though I am not sure if that is autogenerated by autotools or configure.

[1] https://caml.inria.fr/mantis/view.php?id=7133

**Comment by dimpase** [comment]
The local symbol label is just `"L"`, at least it's what `config.h` on OSX says.
However, note that there are labels starting from '.' in some *.as files: in `mpn/x86_64/skylake/sub_n.as`, `skylake/avx/add_err1_n.as`.

I guess that renaming them with something dotless will fix the OSX linking error on skylake, and will allow removing that dodgy `darwin.m4` fix. I'll have a look into this.

**Comment by wbhart** [comment]
There should be a macro for the yasm assembly as well, to get the local symbol prefix correct there too. I don't exactly know what the linker does with local symbols, but it might be something relevant.

**Comment by dimpase** [comment]
from that ocaml link, this looks relevant:
```
Dropping the .section __TEXT,__const directive fixes the problem
```

**Comment by wbhart** [comment]
Yes, it might be worth a try.

**Comment by dimpase** [comment]
the JMPENT workaround is needed for labels dealt with by the OSX linker.
But if no such labels are needed in .as(m) files, they should not be made
visible to the linker in the 1st place.

And the key to this seems to be the right .section type, as per ocaml link.

**Comment by wbhart** [comment]
Yes, I agree. That sounds like it is the issue.

**Comment by dimpase** [comment]
yes, this works on my laptop! let's see if Travis is happy too.

**Comment by dimpase** [comment]
I can confirm that I can at least build for skylakeavx using `--host` option to ./configure. So it's hopefully done. Asking for  tests on real hardware now.

**Comment by dimpase** [comment]
works on Travis/nehalem OSX build too.

**Comment by wbhart** [comment]
Looks good, congratulations!

**Comment by dimpase** [comment]
any chance you do a new release? packaging all these patches against 3.0.0 is no fun at all...

**Comment by wbhart** [comment]
I think a release is the best thing to do. But unfortunately, it is
nontrivial. We have to  fill out all the paperwork, update the version
number, update the .so version, do make dist, test the tarball, update the
website, send out announcements. At least there are no changes for Windows,
which makes life easier.

Unfortunately MPIR still doesn't work with Flint on Windows, due to someone
changing the Windows interface in a rather complicated way.

**Comment by dimpase** [comment]
Do you think these pretty much mechanical changes I did to asm files (renaming labels and putting L() around them) warrant chenges in copyright notices? And if yes, what kind of changes?

**Comment by wbhart** [comment]
No, they do not require updates to copyright, since they can be accomplished automatically by a machine.

**Pull request merged**
